Upload Cleaned Dataset

In [1]:
import pandas as pd
from google.colab import files

# Upload Stage 4 cleaned dataset
uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

# Convert date column
df["date"] = pd.to_datetime(df["date"], errors="coerce")

print("Stage 4 cleaned dataset loaded successfully!")
print("Dataset Shape:", df.shape)

Saving railway_delay_analyzer_finaldataset to railway_delay_analyzer_finaldataset
Stage 4 cleaned dataset loaded successfully!
Dataset Shape: (50000, 40)

Basic Dataset Validation

In [2]:
print("STAGE 5 DATASET VALIDATION")
print("=" * 60)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("Unique Trains:", df["train_no"].nunique())
print("Unique Stations:", df["station_no"].nunique())

print("Start Date:", df["date"].min())
print("End Date:", df["date"].max())

STAGE 5 DATASET VALIDATION
============================================================
Rows: 50000
Columns: 40
Unique Trains: 21
Unique Stations: 29
Start Date: 2025-02-08 00:00:00
End Date: 2026-02-07 00:00:00

Train Performance using groupby() + agg()

Idi mandatory requirement.

In [3]:
train_performance = (
    df.groupby(
        ["train_no", "train_name"]
    )
    .agg(
        total_records=("train_no", "size"),
        average_delay=("delay", "mean"),
        maximum_delay=("delay", "max"),
        minimum_delay=("delay", "min"),
        total_delay=("delay", "sum")
    )
    .reset_index()
)

print("TRAIN PERFORMANCE")
print("=" * 60)

display(train_performance.head(10))

TRAIN PERFORMANCE
============================================================

,train_no,train_name,total_records,average_delay,maximum_delay,minimum_delay,total_delay
0,961,VALLEY QUEEN SPL,504,2.644841,79.0,-8.0,1333.0
1,962,VALLEY QUEEN SPL,477,2.238994,83.0,-21.0,1068.0
2,1021,Unknown,46,297.760870,533.0,25.0,13697.0
3,1022,Unknown,46,348.826087,561.0,153.0,16046.0
4,1023,PUNE KOP SPECIAL,7964,36.430437,301.0,-76.0,290132.0
5,1024,KOP PUNE SPECIAL,7964,16.774485,311.0,-52.0,133592.0
6,1025,DR BALLIA SPL,2797,110.162317,679.0,0.0,308124.0
7,1025,Unknown,861,209.073171,784.0,-4.0,180012.0
8,1026,BUI DR SPL,751,57.615180,544.0,0.0,43269.0
9,1026,Unknown,2886,191.963964,3335.0,0.0,554008.0

Station Performance using groupby() + agg()

In [4]:
station_performance = (
    df.groupby(
        ["station_no", "station_name"]
    )
    .agg(
        total_records=("station_no", "size"),
        average_delay=("delay", "mean"),
        maximum_delay=("delay", "max"),
        minimum_delay=("delay", "min"),
        total_delay=("delay", "sum")
    )
    .reset_index()
)

print("STATION PERFORMANCE")
print("=" * 60)

display(station_performance.head(10))

STATION PERFORMANCE
============================================================

,station_no,station_name,total_records,average_delay,maximum_delay,minimum_delay,total_delay
0,1,BD,316,9.433544,129.0,0.0,2981.0
1,1,BUI,148,41.263514,377.0,0.0,6107.0
2,1,CPR,7,11.714286,67.0,0.0,82.0
3,1,CSMT,2,128.500000,220.0,37.0,257.0
4,1,DNR,12,127.583333,612.0,10.0,1531.0
5,1,DR,348,7.017241,684.0,0.0,2442.0
6,1,DVL,22,9.818182,63.0,0.0,216.0
7,1,GKP,146,31.232877,1070.0,0.0,4560.0
8,1,KBK,159,2.201258,62.0,0.0,350.0
9,1,KOP,362,2.276243,150.0,0.0,824.0

Delayed Trains using Boolean Indexing

In [5]:
delayed_trains = df[
    df["delay"] > 0
].copy()

print("DELAYED TRAIN RECORDS")
print("=" * 60)

print("Total delayed records:", len(delayed_trains))

display(
    delayed_trains[
        [
            "date",
            "train_no",
            "train_name",
            "station_name",
            "delay"
        ]
    ].head(10)
)

DELAYED TRAIN RECORDS
============================================================
Total delayed records: 44444

         date  train_no        train_name station_name  delay
23 2025-04-12       961  VALLEY QUEEN SPL           MJ    1.0
28 2025-04-19       961  VALLEY QUEEN SPL           MJ    3.0
75 2025-06-23       961  VALLEY QUEEN SPL           MJ    6.0
77 2025-06-26       961  VALLEY QUEEN SPL           MJ   72.0
78 2025-06-28       961  VALLEY QUEEN SPL           MJ    5.0
81 2025-07-02       961  VALLEY QUEEN SPL           MJ   11.0
83 2025-07-05       961  VALLEY QUEEN SPL           MJ    1.0
85 2025-07-07       961  VALLEY QUEEN SPL           MJ    4.0
89 2025-07-13       961  VALLEY QUEEN SPL           MJ   11.0
90 2025-07-14       961  VALLEY QUEEN SPL           MJ    4.0

Delay > 15 Minutes using Boolean Indexing + filter()

In [6]:
high_delay = df[
    df["delay"] > 15
].copy()

# Select required columns using filter()
high_delay_selected = high_delay.filter(
    items=[
        "date",
        "train_no",
        "train_name",
        "station_name",
        "delay",
        "weather_condition",
        "congestion_level",
        "operational_disruption"
    ]
)

print("HIGH DELAY RECORDS")
print("=" * 60)

print(
    "Records with delay > 15 minutes:",
    len(high_delay_selected)
)

display(high_delay_selected.head(10))

HIGH DELAY RECORDS
============================================================
Records with delay > 15 minutes: 35619

,date,train_no,train_name,station_name,delay,weather_condition,congestion_level,operational_disruption
77,2025-06-26,961,VALLEY QUEEN SPL,MJ,72.0,Rain,High,Significant delay / traffic regulation
96,2025-07-23,961,VALLEY QUEEN SPL,MJ,22.0,Rain,Moderate,Minor operational delay
97,2025-07-24,961,VALLEY QUEEN SPL,MJ,19.0,Clear,Moderate,Minor operational delay
99,2025-07-27,961,VALLEY QUEEN SPL,MJ,17.0,Clear,Moderate,Minor operational delay
100,2025-07-28,961,VALLEY QUEEN SPL,MJ,28.0,Cloudy,Moderate,Minor operational delay
102,2025-07-31,961,VALLEY QUEEN SPL,MJ,28.0,Rain,Moderate,Minor operational delay
245,2025-06-26,961,VALLEY QUEEN SPL,FLD,16.0,Rain,Moderate,Minor operational delay
263,2025-07-21,961,VALLEY QUEEN SPL,FLD,79.0,Cloudy,Moderate,Significant delay / traffic regulation
264,2025-07-23,961,VALLEY QUEEN SPL,FLD,20.0,Humid/Cloudy,Moderate,Minor operational delay
265,2025-07-24,961,VALLEY QUEEN SPL,FLD,19.0,Rain,Moderate,Minor operational delay

Train Ranking using sort_values()

In [7]:
train_ranking = (
    train_performance
    .sort_values(
        by="average_delay",
        ascending=False
    )
    .reset_index(drop=True)
)

print("TRAIN RANKING BY AVERAGE DELAY")
print("=" * 60)

display(train_ranking.head(10))

TRAIN RANKING BY AVERAGE DELAY
============================================================

,train_no,train_name,total_records,average_delay,maximum_delay,minimum_delay,total_delay
0,1022,Unknown,46,348.826087,561.0,153.0,16046.0
1,1054,Unknown,563,331.028419,1181.0,0.0,186369.0
2,1021,Unknown,46,297.760870,533.0,25.0,13697.0
3,1025,Unknown,861,209.073171,784.0,-4.0,180012.0
4,1030,Unknown,127,195.417323,778.0,0.0,24818.0
5,1026,Unknown,2886,191.963964,3335.0,0.0,554008.0
6,1053,Unknown,862,180.892111,886.0,-29.0,155929.0
7,1140,Unknown,118,161.644068,495.0,-3.0,19074.0
8,1028,Unknown,4692,158.588662,1930.0,0.0,744098.0
9,1027,Unknown,1636,156.405257,1855.0,0.0,255879.0

Station Ranking using sort_values()

In [8]:
station_ranking = (
    station_performance
    .sort_values(
        by="average_delay",
        ascending=False
    )
    .reset_index(drop=True)
)

print("STATION RANKING BY AVERAGE DELAY")
print("=" * 60)

display(station_ranking.head(10))

STATION RANKING BY AVERAGE DELAY
============================================================

,station_no,station_name,total_records,average_delay,maximum_delay,minimum_delay,total_delay
0,10,PCOI,2,648.000000,651.0,645.0,1296.0
1,25,LTT,3,589.000000,1130.0,188.0,1767.0
2,24,TNA,26,575.923077,1181.0,228.0,14974.0
3,23,KYN,26,533.961538,1160.0,162.0,13883.0
4,21,NK,26,471.538462,1141.0,192.0,12260.0
5,12,PCOI,9,451.888889,1573.0,108.0,4067.0
6,22,IGP,26,442.384615,1100.0,148.0,11502.0
7,14,PPI,26,418.884615,1050.0,195.0,10891.0
8,4,ARMU,2,408.500000,561.0,256.0,817.0
9,13,NU,26,408.500000,1034.0,174.0,10621.0

merge() Train Details with Performance

In [9]:
train_details = (
    df[
        [
            "train_no",
            "train_name",
            "type_code"
        ]
    ]
    .drop_duplicates()
)

train_summary = train_performance.merge(
    train_details,
    on=[
        "train_no",
        "train_name"
    ],
    how="left"
)

print("MERGE OPERATION")
print("=" * 60)

print("Train performance and train details merged successfully!")

display(train_summary.head(10))

MERGE OPERATION
============================================================
Train performance and train details merged successfully!

,train_no,train_name,total_records,average_delay,maximum_delay,minimum_delay,total_delay,type_code
0,961,VALLEY QUEEN SPL,504,2.644841,79.0,-8.0,1333.0,EXP-TRAINS
1,962,VALLEY QUEEN SPL,477,2.238994,83.0,-21.0,1068.0,EXP-TRAINS
2,1021,Unknown,46,297.760870,533.0,25.0,13697.0,Unknown
3,1022,Unknown,46,348.826087,561.0,153.0,16046.0,Unknown
4,1023,PUNE KOP SPECIAL,7964,36.430437,301.0,-76.0,290132.0,EXP-TRAINS
5,1024,KOP PUNE SPECIAL,7964,16.774485,311.0,-52.0,133592.0,EXP-TRAINS
6,1025,DR BALLIA SPL,2797,110.162317,679.0,0.0,308124.0,EXP-TRAINS
7,1025,Unknown,861,209.073171,784.0,-4.0,180012.0,Unknown
8,1026,BUI DR SPL,751,57.615180,544.0,0.0,43269.0,EXP-TRAINS
9,1026,Unknown,2886,191.963964,3335.0,0.0,554008.0,Unknown

Create Delay Categories

In [10]:
df["delay_category"] = pd.cut(
    df["delay"],
    bins=[
        -float("inf"),
        0,
        15,
        float("inf")
    ],
    labels=[
        "On Time",
        "Delay 1-15 Minutes",
        "Delay >15 Minutes"
    ]
)

print("Delay categories created successfully!")

print(
    df["delay_category"].value_counts()
)

Delay categories created successfully!
delay_category
Delay >15 Minutes     35619
Delay 1-15 Minutes     8825
On Time                5556
Name: count, dtype: int64

pivot_table() Station-wise Delay Comparison

In [11]:
station_delay_pivot = pd.pivot_table(
    df,
    index="station_name",
    columns="delay_category",
    values="delay",
    aggfunc="count",
    fill_value=0,
    observed=False
)

print("STATION-WISE DELAY COMPARISON")
print("=" * 60)

display(
    station_delay_pivot.head(10)
)

STATION-WISE DELAY COMPARISON
============================================================

delay_category  On Time  Delay 1-15 Minutes  Delay >15 Minutes
station_name
ADVI                  1                   1                 28
AJNI                 20                  10                  0
AK                   20                  50                455
ARA                   0                   2                 32
ARJ                  69                 134                503
ARMU                  0                   0                  4
AVRD                  0                   1                  5
AWB                   0                   0                  4
BAU                   0                   0                 34
BD                   87                 251                187

transform() for Train-level Comparison

Idi mandatory requirement.

In [12]:
df["train_average_delay"] = (
    df.groupby("train_no")["delay"]
    .transform("mean")
)

df["delay_vs_train_average"] = (
    df["delay"] -
    df["train_average_delay"]
)

print("TRAIN-LEVEL TRANSFORM COMPARISON")
print("=" * 60)

display(
    df[
        [
            "train_no",
            "train_name",
            "station_name",
            "delay",
            "train_average_delay",
            "delay_vs_train_average"
        ]
    ].head(10)
)

TRAIN-LEVEL TRANSFORM COMPARISON
============================================================

,train_no,train_name,station_name,delay,train_average_delay,delay_vs_train_average
0,961,VALLEY QUEEN SPL,MJ,0.0,2.644841,-2.644841
1,961,VALLEY QUEEN SPL,MJ,0.0,2.644841,-2.644841
2,961,VALLEY QUEEN SPL,MJ,0.0,2.644841,-2.644841
3,961,VALLEY QUEEN SPL,MJ,0.0,2.644841,-2.644841
4,961,VALLEY QUEEN SPL,MJ,0.0,2.644841,-2.644841
5,961,VALLEY QUEEN SPL,MJ,0.0,2.644841,-2.644841
6,961,VALLEY QUEEN SPL,MJ,0.0,2.644841,-2.644841
7,961,VALLEY QUEEN SPL,MJ,0.0,2.644841,-2.644841
8,961,VALLEY QUEEN SPL,MJ,0.0,2.644841,-2.644841
9,961,VALLEY QUEEN SPL,MJ,0.0,2.644841,-2.644841

transform() for Station-level Comparison

In [13]:
df["station_average_delay"] = (
    df.groupby("station_no")["delay"]
    .transform("mean")
)

df["delay_vs_station_average"] = (
    df["delay"] -
    df["station_average_delay"]
)

print("STATION-LEVEL TRANSFORM COMPARISON")
print("=" * 60)

display(
    df[
        [
            "station_no",
            "station_name",
            "delay",
            "station_average_delay",
            "delay_vs_station_average"
        ]
    ].head(10)
)

STATION-LEVEL TRANSFORM COMPARISON
============================================================

,station_no,station_name,delay,station_average_delay,delay_vs_station_average
0,1,MJ,0.0,13.4447,-13.4447
1,1,MJ,0.0,13.4447,-13.4447
2,1,MJ,0.0,13.4447,-13.4447
3,1,MJ,0.0,13.4447,-13.4447
4,1,MJ,0.0,13.4447,-13.4447
5,1,MJ,0.0,13.4447,-13.4447
6,1,MJ,0.0,13.4447,-13.4447
7,1,MJ,0.0,13.4447,-13.4447
8,1,MJ,0.0,13.4447,-13.4447
9,1,MJ,0.0,13.4447,-13.4447

Save Stage 5 Outputs

In [14]:
# Train performance
train_performance.to_csv(
    "stage5_train_performance.csv",
    index=False
)

# Station performance
station_performance.to_csv(
    "stage5_station_performance.csv",
    index=False
)

# Delayed trains
delayed_trains.to_csv(
    "stage5_delayed_trains.csv",
    index=False
)

# High delay records
high_delay_selected.to_csv(
    "stage5_high_delay_records.csv",
    index=False
)

# Merged train summary
train_summary.to_csv(
    "stage5_train_summary_merged.csv",
    index=False
)

# Pivot table
station_delay_pivot.to_csv(
    "stage5_station_delay_pivot.csv"
)

# Final aggregated dataset
df.to_csv(
    "stage5_aggregated_dataset.csv",
    index=False
)

print("All Stage 5 files saved successfully!")

print("\nFiles Created:")
print("1. stage5_train_performance.csv")
print("2. stage5_station_performance.csv")
print("3. stage5_delayed_trains.csv")
print("4. stage5_high_delay_records.csv")
print("5. stage5_train_summary_merged.csv")
print("6. stage5_station_delay_pivot.csv")
print("7. stage5_aggregated_dataset.csv")

All Stage 5 files saved successfully!

Files Created:
1. stage5_train_performance.csv
2. stage5_station_performance.csv
3. stage5_delayed_trains.csv
4. stage5_high_delay_records.csv
5. stage5_train_summary_merged.csv
6. stage5_station_delay_pivot.csv
7. stage5_aggregated_dataset.csv