Upload Dataset & Read

In [2]:
import pandas as pd
from google.colab import files

# Upload dataset
uploaded = files.upload()

file_name = list(uploaded.keys())[0]

# Read CSV
df = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("Original Shape:", df.shape)

df.head()

Saving railway_delay_analyzer_finaldataset to railway_delay_analyzer_finaldataset
Dataset loaded successfully!
Original Shape: (50000, 40)

,date,train_no,train_name,type_code,station_no,station_name,station_full_name,station_zone,station_address,distance_from_origin,...,scheduled_arrival_datetime,actual_arrival_datetime,arrival_delay_minutes,scheduled_vs_actual_arrival_status,weather_condition,temperature_c,rainfall_mm,congestion_index,congestion_level,operational_disruption
0,2025-02-12,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,"Pali, Rajasthan, India",0.0,...,2025-02-12 09:37,2025-02-12 09:37,0.0,Early/on-time,Cloudy,16.3,0.0,0.27,Low,Normal operations
1,2025-02-13,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,"Pali, Rajasthan, India",0.0,...,2025-02-13 09:37,2025-02-13 09:37,0.0,Early/on-time,Clear,15.8,0.0,0.27,Low,Normal operations
2,2025-02-22,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,"Pali, Rajasthan, India",0.0,...,2025-02-22 09:37,2025-02-22 09:37,0.0,Early/on-time,Cool & Clear,16.6,0.0,0.37,Moderate,Normal operations
3,2025-02-23,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,"Pali, Rajasthan, India",0.0,...,2025-02-23 09:37,2025-02-23 09:37,0.0,Early/on-time,Cloudy,21.8,0.0,0.37,Moderate,Normal operations
4,2025-02-24,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,"Pali, Rajasthan, India",0.0,...,2025-02-24 09:37,2025-02-24 09:37,0.0,Early/on-time,Cloudy,19.7,0.0,0.27,Low,Normal operations

Convert Date Columns

In [3]:
# Convert date column
df["date"] = pd.to_datetime(df["date"], errors="coerce")

# Convert datetime columns
df["scheduled_arrival_datetime"] = pd.to_datetime(
    df["scheduled_arrival_datetime"], errors="coerce"
)

df["actual_arrival_datetime"] = pd.to_datetime(
    df["actual_arrival_datetime"], errors="coerce"
)

print("Date columns converted successfully!")

print("\nData Types:")
print(df[[
    "date",
    "scheduled_arrival_datetime",
    "actual_arrival_datetime"
]].dtypes)

Date columns converted successfully!

Data Types:
date                          datetime64[ns]
scheduled_arrival_datetime    datetime64[ns]
actual_arrival_datetime       datetime64[ns]
dtype: object

Extract Date Information

In [4]:


df["extracted_year"] = df["date"].dt.year
df["extracted_month"] = df["date"].dt.month
df["extracted_day"] = df["date"].dt.day
df["extracted_day_of_week"] = df["date"].dt.day_name()

print("Date information extracted successfully!")

print(df[[
    "date",
    "extracted_year",
    "extracted_month",
    "extracted_day",
    "extracted_day_of_week"
]].head())

Date information extracted successfully!
        date  extracted_year  extracted_month  extracted_day  \
0 2025-02-12            2025                2             12
1 2025-02-13            2025                2             13
2 2025-02-22            2025                2             22
3 2025-02-23            2025                2             23
4 2025-02-24            2025                2             24

  extracted_day_of_week
0             Wednesday
1              Thursday
2              Saturday
3                Sunday
4                Monday

Select / Extract Important Columns

In [5]:


extracted_columns = [
    "date",
    "train_no",
    "train_name",
    "type_code",
    "station_no",
    "station_name",
    "station_full_name",
    "station_zone",
    "distance_from_origin",
    "arrival_day",
    "arrival_time",
    "departure_day",
    "departure_time",
    "delay",
    "year",
    "month",
    "day_of_week",
    "scheduled_arrival_minutes",
    "scheduled_departure_minutes",
    "scheduled_arrival_datetime",
    "actual_arrival_datetime",
    "arrival_delay_minutes",
    "scheduled_vs_actual_arrival_status",
    "weather_condition",
    "temperature_c",
    "rainfall_mm",
    "congestion_index",
    "congestion_level",
    "operational_disruption",
    "extracted_year",
    "extracted_month",
    "extracted_day",
    "extracted_day_of_week"
]

extracted_df = df[extracted_columns].copy()

print("Data extraction completed!")
print("Extracted Shape:", extracted_df.shape)

extracted_df.head()

Data extraction completed!
Extracted Shape: (50000, 33)

,date,train_no,train_name,type_code,station_no,station_name,station_full_name,station_zone,distance_from_origin,arrival_day,...,weather_condition,temperature_c,rainfall_mm,congestion_index,congestion_level,operational_disruption,extracted_year,extracted_month,extracted_day,extracted_day_of_week
0,2025-02-12,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,0.0,1.0,...,Cloudy,16.3,0.0,0.27,Low,Normal operations,2025,2,12,Wednesday
1,2025-02-13,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,0.0,1.0,...,Clear,15.8,0.0,0.27,Low,Normal operations,2025,2,13,Thursday
2,2025-02-22,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,0.0,1.0,...,Cool & Clear,16.6,0.0,0.37,Moderate,Normal operations,2025,2,22,Saturday
3,2025-02-23,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,0.0,1.0,...,Cloudy,21.8,0.0,0.37,Moderate,Normal operations,2025,2,23,Sunday
4,2025-02-24,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,0.0,1.0,...,Cloudy,19.7,0.0,0.27,Low,Normal operations,2025,2,24,Monday

Extract Delayed Train Records

In [6]:


delayed_trains = extracted_df[
    extracted_df["delay"].fillna(0) > 0
].copy()

print("Delayed train records extracted successfully!")
print("Number of delayed records:", len(delayed_trains))

delayed_trains[[
    "date",
    "train_no",
    "train_name",
    "station_name",
    "delay"
]].head()

Delayed train records extracted successfully!
Number of delayed records: 44444

         date  train_no        train_name station_name  delay
23 2025-04-12       961  VALLEY QUEEN SPL           MJ    1.0
28 2025-04-19       961  VALLEY QUEEN SPL           MJ    3.0
75 2025-06-23       961  VALLEY QUEEN SPL           MJ    6.0
77 2025-06-26       961  VALLEY QUEEN SPL           MJ   72.0
78 2025-06-28       961  VALLEY QUEEN SPL           MJ    5.0

Extract Weather & Operational Information

In [7]:
weather_operational_data = extracted_df[[
    "date",
    "train_no",
    "station_name",
    "delay",
    "weather_condition",
    "temperature_c",
    "rainfall_mm",
    "congestion_index",
    "congestion_level",
    "operational_disruption"
]].copy()

print("Weather and operational data extracted!")
print("Shape:", weather_operational_data.shape)

weather_operational_data.head()

Weather and operational data extracted!
Shape: (50000, 10)

,date,train_no,station_name,delay,weather_condition,temperature_c,rainfall_mm,congestion_index,congestion_level,operational_disruption
0,2025-02-12,961,MJ,0.0,Cloudy,16.3,0.0,0.27,Low,Normal operations
1,2025-02-13,961,MJ,0.0,Clear,15.8,0.0,0.27,Low,Normal operations
2,2025-02-22,961,MJ,0.0,Cool & Clear,16.6,0.0,0.37,Moderate,Normal operations
3,2025-02-23,961,MJ,0.0,Cloudy,21.8,0.0,0.37,Moderate,Normal operations
4,2025-02-24,961,MJ,0.0,Cloudy,19.7,0.0,0.27,Low,Normal operations

Save Extracted Data

In [8]:

extracted_df.to_csv(
    "stage3_extracted_data.csv",
    index=False
)

# Save delayed records
delayed_trains.to_csv(
    "stage3_delayed_train_records.csv",
    index=False
)

# Save weather and operational data
weather_operational_data.to_csv(
    "stage3_weather_operational_data.csv",
    index=False
)

print("Files saved successfully!")
print("\nCreated files:")
print("1. stage3_extracted_data.csv")
print("2. stage3_delayed_train_records.csv")
print("3. stage3_weather_operational_data.csv")

Files saved successfully!

Created files:
1. stage3_extracted_data.csv
2. stage3_delayed_train_records.csv
3. stage3_weather_operational_data.csv